### ISSUE TITLE
World Load Issue

### ISSUE THREAD

**Issue by BDCarrillo** [0x00002a/Accelerometer#1]
Another player lost power, and their Accelerometer.cfg become corrupted.  This led to a recurring error:

"Error: Error during loading session:System.InvalidOperationException: There is an error in XML document (1, 1). ---> System.Xml.XmlException: '.', hexadecimal value 0x00, is an invalid character. Line 1, position 1."

User deleted config and was able to restart.  Recommend wrapping config loading/parsing inside a try/catch and implementing defaults on error

**Comment by 0x00002a** [comment]
Yeah good shout, shouldn't be crashing the game for sure
